nodeLinker: pnpm

enableGlobalCache: true

# Keep cache within project directory to avoid cross-device linking issues
# This folder is only used when enableGlobalCache is true
globalFolder: .yarn/cache

yarnPath: .yarn/releases/yarn-4.6.0.cjs
