name: Manually publish RUST packages

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main

jobs:
  publish:
    name: Publish packages
    runs-on: ubuntu-latest-4xlarge
    permissions:
      contents: read
      packages: read
    container:
      image: ghcr.io/layerresearch/devcon:1.0.0-bookworm
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      options: --privileged
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Build
        run: |
          cargo build --release --verbose

      - name: Publish
        run: |
          cd hpfile && cargo publish --token ${CRATES_TOKEN}
          cd qmdb && cargo publish --token ${CRATES_TOKEN}
        env:
          CRATES_TOKEN: ${{ secrets.CRATES_TOKEN }}
